from __future__ import annotations

from trajectory.sampling import SAMPLING_METADATA_COLUMNS

UTILITY_LAMBDAS = (0.0, 0.25, 0.5, 1.0, 2.0)
UTILITY_VALUE_COLUMNS = (
    "u_query_lamT_0",
    "u_query_lamT_025",
    "u_query_lamT_05",
    "u_query_lamT_1",
    "u_query_lamT_2",
)
NEED_QUERY_COLUMNS = (
    "need_query_lamT_0",
    "need_query_lamT_025",
    "need_query_lamT_05",
    "need_query_lamT_1",
    "need_query_lamT_2",
)
UTILITY_COLUMNS = (
    "split",
    "problem_id",
    "family",
    "dimension",
    "prefix_algorithm",
    "seed",
    "FE",
    "FE_ratio",
    *SAMPLING_METADATA_COLUMNS,
    "query_id",
    "query_protocol",
    "query_feature_columns",
    "sample_design_id",
    "FE_total",
    "FE_prefix",
    "FE_query",
    "FE_no_query_optimization",
    "FE_query_optimization",
    "default_algorithm",
    "no_query_algorithm",
    "selection_reference_default_algorithm",
    "selection_reference_protocol",
    "selector_prediction_source",
    "selector_target_transform",
    "selected_algorithm",
    "selected_action",
    "selected_equals_default",
    "selected_equals_prefix",
    "handoff_required",
    "skip_switches_from_prefix",
    "no_query_transition_mode",
    "query_transition_mode",
    "handoff_type",
    "p_skip",
    "p_query",
    "selected_action_loss",
    "best_observed_algorithm",
    "best_observed_loss",
    "selected_matches_best_observed",
    "potential_gain_raw",
    "selector_regret_raw",
    "performance_norm_scale",
    "potential_gain_norm",
    "selector_regret_decomposition_norm",
    "performance_gain_raw",
    "performance_gain_norm",
    "runtime_query",
    "runtime_selection",
    "runtime_no_query_optimization",
    "runtime_query_optimization",
    "time_cost_norm",
    "memory_cost_norm",
    *UTILITY_VALUE_COLUMNS,
    *NEED_QUERY_COLUMNS,
)
